[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:chrome-debug-1]
command=/usr/bin/chromium
    --headless=new
    --no-sandbox
    --no-zygote
    --enable-gpu
    --ignore-gpu-blocklist
    --use-angle=vulkan
    --disable-gpu-sandbox
    --disable-dev-shm-usage
    --disable-background-networking
    --disable-component-update
    --disable-blink-features=AutomationControlled
    --disable-infobars
    --remote-debugging-port=%(ENV_CDP_PORT_1)s
    --user-data-dir=/tmp/chrome-profile-1
autostart=true
autorestart=true
stdout_logfile=/var/log/chrome-debug-1.log
stderr_logfile=/var/log/chrome-debug-1-err.log
priority=10

[program:chrome-debug-2]
command=/usr/bin/chromium
    --headless=new
    --no-sandbox
    --no-zygote
    --enable-gpu
    --ignore-gpu-blocklist
    --use-angle=vulkan
    --disable-gpu-sandbox
    --disable-dev-shm-usage
    --disable-background-networking
    --disable-component-update
    --disable-blink-features=AutomationControlled
    --disable-infobars
    --remote-debugging-port=%(ENV_CDP_PORT_2)s
    --user-data-dir=/tmp/chrome-profile-2
autostart=true
autorestart=true
stdout_logfile=/var/log/chrome-debug-2.log
stderr_logfile=/var/log/chrome-debug-2-err.log
priority=10
