"""Type stubs for the void_crawl._ext native extension module.

Internal — import from ``void_crawl`` instead.
"""

from __future__ import annotations

class PooledTab:
    use_count: int

    async def goto(self, url: str, timeout: float = 30.0) -> str | None: ...
    async def navigate(self, url: str) -> None: ...
    async def wait_for_navigation(self) -> None: ...
    async def content(self) -> str: ...
    async def title(self) -> str | None: ...
    async def url(self) -> str | None: ...
    async def evaluate_js(self, expression: str) -> object: ...
    async def screenshot_png(self) -> bytes: ...
    async def query_selector(self, selector: str) -> str | None: ...
    async def query_selector_all(self, selector: str) -> list[str]: ...
    async def click_element(self, selector: str) -> None: ...
    async def type_into(self, selector: str, text: str) -> None: ...
    async def set_headers(self, headers: dict[str, str]) -> None: ...
    async def wait_for_stable_dom(
        self, timeout: float = 10.0, min_length: int = 5000, stable_checks: int = 5
    ) -> bool: ...
    async def wait_for_network_idle(self, timeout: float = 30.0) -> str | None: ...

class _AcquireContext:
    async def __aenter__(self) -> PooledTab: ...
    async def __aexit__(
        self, exc_type: object = None, exc_val: object = None, exc_tb: object = None
    ) -> bool: ...

class _PoolContext:
    async def __aenter__(self) -> BrowserPool: ...
    async def __aexit__(
        self, exc_type: object = None, exc_val: object = None, exc_tb: object = None
    ) -> bool: ...

class _PoolParamsContext:
    async def __aenter__(self) -> BrowserPool: ...
    async def __aexit__(
        self, exc_type: object = None, exc_val: object = None, exc_tb: object = None
    ) -> bool: ...

class BrowserPool:
    @classmethod
    def from_env(cls) -> _PoolContext: ...
    @classmethod
    def _from_params(
        cls,
        browsers: int,
        tabs_per_browser: int,
        tab_max_uses: int,
        tab_max_idle_secs: int,
        headless: bool,
        no_sandbox: bool,
        stealth: bool,
        ws_urls: list[str],
        proxy: str | None,
        chrome_executable: str | None,
        extra_args: list[str],
    ) -> _PoolParamsContext: ...
    async def warmup(self) -> None: ...
    def acquire(self) -> _AcquireContext: ...
    async def release(self, tab: PooledTab) -> None: ...
    async def __aenter__(self) -> BrowserPool: ...
    async def __aexit__(
        self, exc_type: object = None, exc_val: object = None, exc_tb: object = None
    ) -> bool: ...

class Page:
    async def goto(self, url: str, timeout: float = 30.0) -> str | None: ...
    async def navigate(self, url: str) -> None: ...
    async def wait_for_navigation(self) -> None: ...
    async def content(self) -> str: ...
    async def title(self) -> str | None: ...
    async def url(self) -> str | None: ...
    async def evaluate_js(self, expression: str) -> object: ...
    async def screenshot_png(self) -> bytes: ...
    async def pdf_bytes(self) -> bytes: ...
    async def query_selector(self, selector: str) -> str | None: ...
    async def query_selector_all(self, selector: str) -> list[str]: ...
    async def click_element(self, selector: str) -> None: ...
    async def type_into(self, selector: str, text: str) -> None: ...
    async def set_headers(self, headers: dict[str, str]) -> None: ...
    async def wait_for_stable_dom(
        self, timeout: float = 10.0, min_length: int = 5000, stable_checks: int = 5
    ) -> bool: ...
    async def wait_for_network_idle(self, timeout: float = 30.0) -> str | None: ...
    async def close(self) -> None: ...

class BrowserSession:
    def __init__(
        self,
        *,
        headless: bool = True,
        ws_url: str | None = None,
        stealth: bool = True,
        no_sandbox: bool = False,
        proxy: str | None = None,
        chrome_executable: str | None = None,
        extra_args: list[str] | None = None,
    ) -> None: ...
    async def launch(self) -> None: ...
    async def new_page(self, url: str) -> Page: ...
    async def version(self) -> str: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> BrowserSession: ...
    async def __aexit__(
        self, exc_type: object = None, exc_val: object = None, exc_tb: object = None
    ) -> bool: ...
